owner: cwdaniel
repo: status

sites:
  # GrowTales
  - name: GrowTales
    url: https://growtalesai.com
  - name: GrowTales API
    url: https://api.growtalesai.com

  # Portfolio
  - name: Cincinnati Codes
    url: https://cincinnaticodes.com
  - name: Full Stack Code Ninja
    url: https://fullstackcodeninja.com

  # Apps
  - name: GoQRly
    url: https://goqrly.com
  - name: SnackVote
    url: https://snackvote.com
  - name: Vaulted Photos
    url: https://vaultedphotos.com
  - name: I Need Pokemon Cards
    url: https://ineedpokemoncards.com
  - name: Sanctuary Sight
    url: https://sanctuarysight.com
  - name: Tatted Monkeys
    url: https://tattedmonkeys.com

  # Tactical Warfare
  - name: Tactical Warfare Protocol
    url: https://tacticalwarfareprotocol.com
  - name: TWP Mobile API
    url: https://mobile-api.tacticalwarfareprotocol.com
  - name: TWP Admin
    url: https://secure-admin.tacticalwarfareprotocol.com

status-website:
  cname: status.cincinnaticodes.com
  logoUrl: https://cincinnaticodes.com/logo.png
  name: Service Status
  theme: dark

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "*/5 * * * *"
  uptime: "*/5 * * * *"

i18n:
  activeIncidents: Active incidents
  allSystemsOperational: All systems operational
  incidentReport: Incident report for
```

**5. Commit the changes**

Click "Commit changes"

**6. Wait ~5 minutes**

GitHub Actions will run and build the site.

**7. Add DNS in Cloudflare:**
```
status.cincinnaticodes.com  CNAME  →  YOUR_GITHUB_USERNAME.github.io  (DNS only, proxy OFF)
